<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_1_PlcTask" Id="{3f92f9bc-a1dd-43f7-bd6e-fa51ae4184b4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_MR1K4_SOMS();
PRG_MR2K4_KBO();
PRG_MR3K4_KBO();
PRG_MR4K4_KBO();
PRG_MR5K4_KBO();
PRG_SL2K4_SCATTER();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>